git-debimport ifupdown_0.7.48.1.tar.xz

diff --git a/debian/networking.init b/debian/networking.init
--- a/debian/networking.init
+++ b/debian/networking.init
@@ -12,6 +12,7 @@
 PATH="/sbin:/bin"
 RUN_DIR="/run/network"
 IFSTATE="$RUN_DIR/ifstate"
+STATEDIR="$RUN_DIR/state"
 
 [ -x /sbin/ifup ] || exit 0
 [ -x /sbin/ifdown ] || exit 0
@@ -24,6 +25,7 @@ VERBOSE=no
 
 [ -f /etc/default/networking ] && . /etc/default/networking
 
+verbose=""
 [ "$VERBOSE" = yes ] && verbose=-v
 
 process_exclusions() {
@@ -46,6 +48,9 @@ check_ifstate() {
 	if ! mkdir -p "$RUN_DIR" ; then
 	    log_failure_msg "can't create $RUN_DIR"
 	    exit 1
+	fi
+	if ! chown root:netdev "$RUN_DIR" ; then
+	    log_warning_msg "can't chown $RUN_DIR"
 	fi
     fi
     if [ ! -r "$IFSTATE" ] ; then
@@ -155,7 +160,7 @@ reload)
 	process_options
 
 	log_action_begin_msg "Reloading network interfaces configuration"
-	state=$(cat /run/network/ifstate)
+	state=$(ifquery --state)
 	ifdown -a --exclude=lo $verbose || true
 	if ifup --exclude=lo $state $verbose ; then
 	    log_action_end_msg $?
