git-debimport ifupdown_0.7.53.1.tar.xz

diff --git a/debian/testbuild-linux b/debian/testbuild-linux
--- a/debian/testbuild-linux
+++ b/debian/testbuild-linux
@@ -178,7 +178,7 @@ EOF
 
 cat >tests/testcase.3 <<EOF
 # RUN: -a
-auto eth0
+auto eth0 eth1
 iface eth0 inet static
   address 1.2.3.4
   netmask 255.255.255.0
@@ -205,6 +205,16 @@ iface eth0 inet6 static
   dad-attempts 0
 iface eth0 inet6 static
   address /
+  dad-attempts 0
+
+iface eth1 inet6 static
+  address 3ffe:ffff:100:f102::1/64
+  gateway 3ffe:ffff:100:f102::fff
+  dad-attempts 0
+iface eth1 inet6 static
+  address 3ffe:ffff:100:f102::6/64
+  gateway 3ffe:ffff:100:f102::fff
+  accept_ra 1
   dad-attempts 0
 EOF
 cat >tests/up.3 <<EOF
@@ -281,6 +291,26 @@ run-parts --exit-on-error --verbose /etc/network/if-up.d
 Configuring interface eth0=eth0 (inet6)
 Missing required variable: address
 Missing required configuration variables for interface eth0/inet6.
+Configuring interface eth1=eth1 (inet6)
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+modprobe -q net-pf-10 > /dev/null 2>&1 || true # ignore failure.
+
+sysctl -q -e -w net.ipv6.conf.eth1.accept_ra=0
+sysctl -q -e -w net.ipv6.conf.eth1.autoconf=0
+ip link set dev eth1   up
+ip -6 addr add 3ffe:ffff:100:f102::1/64  dev eth1 
+ ip -6 route add default via 3ffe:ffff:100:f102::fff dev eth1 
+run-parts --exit-on-error --verbose /etc/network/if-up.d
+Configuring interface eth1=eth1 (inet6)
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+modprobe -q net-pf-10 > /dev/null 2>&1 || true # ignore failure.
+
+sysctl -q -e -w net.ipv6.conf.eth1.accept_ra=1
+sysctl -q -e -w net.ipv6.conf.eth1.autoconf=0
+ip link set dev eth1   up
+ip -6 addr add 3ffe:ffff:100:f102::6/64  dev eth1 
+ ip -6 route add default via 3ffe:ffff:100:f102::fff dev eth1 
+run-parts --exit-on-error --verbose /etc/network/if-up.d
 run-parts --exit-on-error --verbose /etc/network/if-up.d
 EOF
 
@@ -514,11 +544,64 @@ cat >tests/up.10 <<EOF
 ====stdout====
 ====stderr====
 Parsing file /dev/null
-Parsing file tests/null
 run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
 run-parts --exit-on-error --verbose /etc/network/if-up.d
 EOF
 
+cat >tests/testcase.11 <<EOF
+# RUN: -a
+auto lo eth0
+
+iface eth0 inet static
+  address 1.2.3.4/24
+
+iface lo inet loopback
+  pre-up configure lo
+  post-down deconfigure lo
+EOF
+cat >tests/up.11 <<EOF
+====stdout====
+====stderr====
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+Configuring interface lo=lo (inet)
+configure lo
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+ip link set dev lo up
+run-parts --exit-on-error --verbose /etc/network/if-up.d
+Configuring interface eth0=eth0 (inet)
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+ip addr add 1.2.3.4/255.255.255.0 broadcast 1.2.3.255 	  dev eth0 label eth0
+ip link set dev eth0   up
+
+run-parts --exit-on-error --verbose /etc/network/if-up.d
+run-parts --exit-on-error --verbose /etc/network/if-up.d
+EOF
+
+cat >tests/testcase.12 <<EOF
+auto lo eth0
+
+iface
+EOF
+cat >tests/up.12 <<EOF
+====stdout====
+====stderr====
+tests/testcase.12:3: too few parameters for iface line
+./ifup: couldn't read interfaces file "tests/testcase.12"
+EOF
+
+# don't create the input file for this testcase
+# cat >tests/testcase.13
+cat >tests/up.13 <<EOF
+====stdout====
+====stderr====
+warning: couldn't open interfaces file "tests/testcase.13"
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+ip link set up dev lo 2>/dev/null
+Configuring interface lo=lo (inet)
+run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
+run-parts --exit-on-error --verbose /etc/network/if-up.d
+run-parts --exit-on-error --verbose /etc/network/if-up.d
+EOF
 
 result=true
 for test in 1 2 3 4 5 6 7 8 9 10; do
@@ -531,6 +614,25 @@ for test in 1 2 3 4 5 6 7 8 9 10; do
 
         echo "Testcase $test: $args"
         
+        if diff -ub tests/up.$test tests/up-res.$test; then
+                echo "(okay)"
+        else
+                echo "(failed)"
+                result=false
+        fi
+        echo "=========="
+done
+
+for test in 11 12 13; do
+        args="-a"
+        ./ifup -nv --force -i tests/testcase.$test $args \
+                >tests/up-res-out.$test 2>tests/up-res-err.$test || 
+                true
+        (echo "====stdout===="; cat tests/up-res-out.$test
+         echo "====stderr===="; cat tests/up-res-err.$test) > tests/up-res.$test
+
+        echo "Testcase $test: $args"
+
         if diff -ub tests/up.$test tests/up-res.$test; then
                 echo "(okay)"
         else
